version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{ .Version }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
